services:
  postgres:
    container_name: postgres-gs-app
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres:15
      POSTGRES_PASSWORD: Omotosho3664!
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: game-store-app-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
    driver: local
